drop table if exists export;
drop table if exists import;
drop table if exists retrieve;
drop table if exists delivery;
drop table if exists tax_info;
drop table if exists item_via_city;
drop table if exists log;
drop table if exists item;
drop table if exists city;
drop table if exists container;
drop table if exists courier;
drop table if exists ship;
drop table if exists company;

delete from export;
delete from import;
delete from retrieve;
delete from delivery;
delete from tax_info;
delete from item_via_city;
delete from log;
delete from item;
delete from city;
delete from container;
delete from courier;
delete from ship;
delete from company;
